### ISSUE TITLE
Using this library in a MFC project

### ISSUE THREAD

**Issue by flaviu22** [Meteosource/meteosource_cpp#1]
I intend to use this library in a MFC project. I have included the source code, and I encountered the following error:

`data.cpp(540): fatal error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "pch.h"' to your source?`

Of course, I have put that include, but then I have met another errors:

```
error C2593: 'operator [' is ambiguous
1>c:\project\MyProject\jsoncpp\json\value.h(454): note: could be 'const Json::Value &Json::Value::operator [](int) const'
1>c:\project\MyProject\jsoncpp\json\value.h(453): note: or       'const Json::Value &Json::Value::operator [](Json::Value::ArrayIndex) const'
1>c:\project\MyProject\meteosource_cpp\data.cpp(94): note: while trying to match the argument list '(const Json::Value, size_t)'
1>c:\project\MyProject\meteosource_cpp\data.cpp(94): error C2512: 'MinuteData::MinuteData': no appropriate default constructor available

```
Did you use it this code in a MFC application ? I have setup a c++17 language, the errrors ... how can I overcome this erros ?

**Comment by Meteosource** [comment]
Hello @flaviu22,
thank you for your message. This seems to be problem specific to running `jsoncpp` under Windows. `Meteosource_cpp` library is being developed and tested under Linux only, so unfortunatelly I am not able to help you with this.

Meteosource team
